backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

# These settings let you edit content locally without pushing to GitHub
local_backend: true

# Media settings
media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "projects"
    label: "Projects"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          default: "",
          required: true,
        }
      - {
          label: "Thumbnail",
          name: "thumbnail",
          widget: "image",
          required: false,
          allow_multiple: false,
        }
      - {
          label: "Description",
          name: "description",
          widget: "text",
          required: true,
        }
      - {
          label: "Status",
          name: "status",
          widget: "select",
          options: ["draft", "in-progress", "completed"],
          default: "draft",
        }
      - {
          label: "Technologies",
          name: "technologies",
          widget: "list",
          required: true,
          min: 1,
          field: { label: "Technology", name: "tech", widget: "string" },
        }
      - {
          label: "GitHub URL",
          name: "github",
          widget: "string",
          required: false,
          pattern:
            [
              "^https://github.com/.+/.+$",
              "Must be a valid GitHub repository URL",
            ],
        }
      - {
          label: "Live URL",
          name: "live",
          widget: "string",
          required: false,
          pattern:
            [
              "^https?://.*",
              "Must be a valid URL starting with http:// or https://",
            ],
        }
      - {
          label: "Featured",
          name: "featured",
          widget: "boolean",
          default: false,
          required: false,
        }
      - { label: "Content", name: "body", widget: "markdown", required: true }

  - name: "notes"
    label: "Notes"
    folder: "content/notes"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          default: "",
          required: true,
        }
      - {
          label: "Description",
          name: "description",
          widget: "text",
          required: true,
        }
      - {
          label: "Category",
          name: "category",
          widget: "select",
          options: ["Development", "Design", "Tutorial", "Tips", "Other"],
          required: true,
        }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Content", name: "body", widget: "markdown", required: true }
