backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/images
public_folder: images
collections:
  - name: "projects"
    label: "Projects"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Content", name: "content", widget: "markdown" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - { label: "Year", name: "year", widget: "string" }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Team", name: "team", widget: "string" }
      - {
          label: "Awards",
          name: "awards",
          widget: "list",
          fields: [{ label: "Award", name: "award", widget: "string" }],
        }

      - { label: "Gallery Image 1", name: "gallery_image_1", widget: "image" }
      - { label: "Gallery Image 2", name: "gallery_image_2", widget: "image" }
      - { label: "Gallery Image 3", name: "gallery_image_3", widget: "image" }
      - {
          label: "Live Preview Link",
          name: "live_preview_link",
          widget: "string",
        }
